apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ledger-api
  namespace: argocd

spec:
  project: default
  spec:
    ignoreDifferences:
      - group: kyverno.io
        kind: ClusterPolicy
        managedFieldsManagers:
          - kyverno
        jsonPointers:
        - /status
        - /metadata/generation
        - /metadata/resourceVersion
        - /metadata/uid
        - /metadata/annotations/argocd.argoproj.io~1tracking-id

  source:
    repoURL: https://github.com/stormshadow47/dodo-devsecops-assignment.git
    targetRevision: main
    path: Task-1-Deploy-Ledger-API/deploy

  destination:
    server: https://kubernetes.default.svc
    namespace: payments

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true