sonar.projectKey=dodo-devsecops-assignment
sonar.organization=stormshadow47
sonar.sources=Task-1-Deploy-Ledger-API/app
sonar.sourceEncoding=UTF-8
sonar.python.version=3
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc
sonar.coverage.exclusions=**/test_*.py
sonar.branch.name=main
