apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ledger-api
  namespace: payments
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ledger-api
  namespace: payments
subjects:
  - kind: ServiceAccount
    name: ledger-api
    namespace: payments
roleRef:
  kind: Role
  name: ledger-api
  apiGroup: rbac.authorization.k8s.io
