---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    VAULT_AUTH_KEY: AgAaQCb0kG/CawwPMYlrRn8v1Kf474OsRaFSlKiYuyuEhlFQvRTzVndzCiWjILOw+GQ4fr05dOUEF1JiD8fxf31Dkjx61EimLqb0X/MAVy24ebKpEga3l1H5h5/BByVAJ+Jq0vTh6BRLYuUBIIzQhlAJROHBVgOXRWtYRWSZhwW9cqbbNnCUeFj/5GBBLfJKzEXGbJinNVX+JMxXn5zQDiAEySmYIO61o+MTDftk+U26LfL/FmMB14lBFeAaefN2ntm7tnt2GFhq1UHsXQsBnUNcbJkt/BSY9067JdATNP5ypY9bzJS+rOvSnbwJG0s6wK3LstVbcIm+hm8EjS7bNTgJEZUgIihwBKwsnTBR/Ne1EVcbfiwloUcxiwZ9NWIdo/JoOaWCipu1NPhNNLi+Mr7PrTOL4LxywPvRyVf1l8kyqqmB6qut0sKdlNZQmPJH2NpeoBHn8rzl8PVVZ8WmsAqi64UJknYp0HEoHPVQt+qiu70L84LkRKAKkmXy2wOtvPl/3aQQQOWAtN6TtCsTEPR/3KCbAAcxbwpRmTPh78GNLSQMqyUcsnFlhsLGhCrlrrMFXjNa53M3rxU/6YJWw/XaWpzOe1jnGori/p10gAsrortv+U+VvjeM/DCGNUVxaOKlCOBfmm3OEq17rUYeEVhWUj7R5pA01AwPiqKq5U+yRUHsOzpGsnjtjsSnhX/PstZFSC1mZgsh/57+sBv1KZ8e/FnwCJRhnvo9V/I=
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
