---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    VAULT_AUTH_KEY: AgAh0s2Lw8AUEDjSHu565WkhIEMqAQFLuMEAGCNU7B7fgEtojyW1P2pepyNtBszvCNQEJoTbnKRz0n8m3gyblgjtm7L3OMlJuQtn/A/eRPGcH+a8l2zycdkiotzSUjOAIlXi1PUrAk7kS5L7vPF292ilHTse++eD7FbdQXGT41227KUDFkmDnJJajd65zGpybaUke6SVUYim9R04BbkZJReKEpiLkQ89Cg5hmKJR7/aHfy7VHymYU4dXpHPu6PVLrAGyMIBX3VclZ9rlKm3pYUH+dFpLr4SnTgfCmRZ8nBTf8rZsGNil6NP90gjGxpkej15/VPj6T7TwG+hhXS1+XBtEfK4lDOHowIdYzbnC8FW/YM6yZ1afawL9rTefsE30IUAHNJDu11YaKJMnJ4VfomM2KsGOl0/INV9bsr+YzqvA+++0n71NKL3wYI1JUmbxy5jqDGCZH60VAvijKOc1T3AKMySjKAuOtUSaf2Rn32NsrrusmDL+rmMb/GAG5UoKr4e3ucyvTPona1FbUc8JEA81bghlEdpSM4kXQefHNpUr+McuXUSb+75ujlUYtGeQ3RwMzlY/i5l2rogE0C1rgbwMhKyKZ7B1/eGhO9Ui2RcKpUr+fYSrsRVvp9SrJXpYc/vxgnWHJYesYUJSFl0H3FkxR7Sf4McljTwX7WZABDfdCZh5g0iPxgcNigjRkyRWJXuEeBNa9SsZ/PkwZXEgueVte7E1yRhlZUaRA9M=
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
