---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    VAULT_AUTH_KEY: AgCIB25lmNltmIFVWAmhbyhVyr/16YC/VJJc9l+b3HpGNwSX+4g9q+nGi9a67YgdghuxgScXSOOhfCmOOe0ySAJPdppVe5bO3TN7YQfxVELB4Gez5c0uFQ+9ITcskfKJuMcOyyI7Ui+tJFyB94VXPYZKGS44ELbply47cjlwjtRGjMP5Yu2EokpnPTulqwJuZPz5j2wkUcP51D/ES8Mky29Lh1Khi8HcM1VbzysWgbvHS/DrmWfszfAyH3epkMqMP4fRixPsVM0yrRb3MrVVJCc6bzuzLmLUmHLjIF587m8GdOzuuVl7ZqnvaUfIL5Ag9+dcfX7secDtgrmV4JBUkYcbd5vvDiP4qhuZxeLwPtReAJdSE+2hvz+soytJ/5yNS/v7kK6MQdzN+NHcZdrVcqnHMHv034MvdJ6+0+qt3imW7hc1NHiE7u0N8zyMaSUzbZBIfhTSX6Lp3xRw3A1zFpPLihErHVJj/58Z/sU3J+2nCBPre3E0z1s9jNRzyvRZQkPWsTGkHQWKRvNR8cFTmLBFOc/edM2rblFBDv7/sky3XzC7+pB7ojMjH4z/GUKXnYW9BB1WY990d28zybDt2qJLb02dmc2l59S+JhbelS9Ox6xb7tIuvkPwfVbo/RbF6u+Su16f6SlhRYq5gbPaofhAZow8YmEW3J2VqQRtgYRC2qbOVnZPpxeiNQcKtHsmdo5j5ckYq6oVFdpITnvbp6Qg1GaPvjsQ7TrHYCU=
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
