name: Build and Secure Container

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/ledger-api

jobs:
  build-security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/security-audit


      - name: Install Gitleaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz
          tar -xzf gitleaks_8.24.3_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/
          gitleaks version


      - name: Run Gitleaks
        run: |
          gitleaks detect \
            --source . \
            --redact \
            --verbose \
            --exit-code 1


      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

          trivy --version

      - name: Run Trivy Filesystem Scan
        run: |
          trivy fs \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            Task-1-Deploy-Ledger-API

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Task-1-Deploy-Ledger-API/app
          file: ./Task-1-Deploy-Ledger-API/app/Dockerfile
          load: true
          push: false
          tags: |
            ledger-api:ci
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Run Trivy Image Scan
        run: |
          trivy image \
            --severity CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            --format table \
            ledger-api:ci

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
